package main

import (
	"bytes"
	"flag"
	"html/template"
	"io/ioutil"
	"log"
	"net/http"
	"regexp"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"
	"github.com/yuin/goldmark/text"
)

// MenuItem is used to build a nav menu for the H1 elements on a page.  Each H1 Element get's
// a link in the nav
type MenuItem struct {
	Text string
	ID   string
}

// PageData is passed to the HTML Template
// Menu is the MenuItem's generated from H1 elements
// Body is the HTML generated by goldmark
type PageData struct {
	Menu []MenuItem
	Body template.HTML
}

var (
	addr  = flag.String("addr", "0.0.0.0:8080", "Address for listening")
	root  = flag.String("root", ".", "Root directory for serving files")
	templ = flag.String("layout", "layout.html", "Layout template for Markdown pages")

	MarkdownSuffix = regexp.MustCompile(`(?i).*\.md$`)

	// If No HTML template is found, this will be used be default.
	htmlText = `
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
		<style>
		</style>
	</head>
	<body>
		<nav class="navbar sticky-top navbar-light">
			{{range .Menu}}
			<a class="nav-item nav-link" href="#{{.ID}}">{{.Text}}</a>
			{{end}}
		</nav>
		<div>
			{{.Body}}
		</div>
	</body>
</html>
`
	defaultTemplate = template.Must(template.New("html").Parse(htmlText))
)

func markdownHandler(w http.ResponseWriter, r *http.Request) {
	var markdown = goldmark.New(
		goldmark.WithExtensions(extension.GFM,
			extension.Typographer,
			NewHeaderDivExtension(),
		),
		goldmark.WithParserOptions(
			parser.WithAutoHeadingID(),
		),
		goldmark.WithRendererOptions(
			html.WithUnsafe(),
		),
	)
	var page PageData

	// Read in the source markdown
	source, err := ioutil.ReadFile(*root + r.URL.Path)
	if err != nil {
		http.NotFound(w, r)
		return
	}

	// Render the Markdown to HTML in the buffer
	var buf bytes.Buffer
	n := markdown.Parser().Parse(text.NewReader(source))
	if err := markdown.Renderer().Render(&buf, source, n); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	page.Body = template.HTML(buf.Bytes())

	// Walk nodes to find Headers.  H1 elements will be added to the Nav menu
	n = n.FirstChild()
	for n != nil {
		h, ok := n.(*ast.Heading)
		if ok && h.Level == 1 {
			id, found := h.Attribute([]byte("id"))
			if found {
				page.Menu = append(page.Menu, MenuItem{
					string(h.Text(source)),
					string(id.([]byte)),
				})
			}
		}

		n = n.NextSibling()
	}

	// Attempt to use a template file, otherwise use the built-in template
	t, err := template.ParseGlob(*templ)
	if err != nil {
		t = defaultTemplate
	}
	// Finally write it all to the client
	if err := t.Execute(w, page); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}

}

// Requests for Markdown files are sent to the markdownHandler,
// all other requests are handled by http.FileServer
func router(w http.ResponseWriter, r *http.Request) {
	// Instead of looking for index.html pages, look for index.md pages
	if strings.HasSuffix(r.URL.Path, "/") {
		r.URL.Path += "index.md"
	}

	if MarkdownSuffix.MatchString(r.URL.Path) {
		markdownHandler(w, r)
	} else {
		http.FileServer(http.Dir(*root)).ServeHTTP(w, r)
	}
}

func main() {
	flag.Parse()
	if *root == "" {
		*root = "."
	}

	http.HandleFunc("/", router)

	log.Fatal(http.ListenAndServe(*addr, nil))
}
